# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Compile PHAR"

on:
    push:
        branches:
            - "master"
        tags:
            - '*'

jobs:
    compile:
        name: "Compile PHAR"
        runs-on: "ubuntu-latest"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"
              with:
                  fetch-depth: 0

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  coverage: "none"
                  php-version: "7.4"
                  tools: composer:v1

            - name: "Cache dependencies"
              uses: "actions/cache@v2"
              with:
                  path: "~/.composer/cache"
                  key: "php-7.4-composer-${{ hashFiles('**/composer.json') }}"
                  restore-keys: "php-7.4-composer-"

            - name: "Install dependencies"
              run: "composer install --no-interaction --no-progress --no-suggest --no-dev"

            - name: "Download box"
              run: wget -O box.phar https://github.com/box-project/box/releases/download/${BOX_VERSION}/box.phar
              env:
                  BOX_VERSION: 3.11.0

            - name: "Prepare pem File"
              env:
                  PHAR_PRIVATE: ${{ secrets.PHAR_PRIVATE }}
              run: echo "$PHAR_PRIVATE" > .github/phar-private.pem

            - name: "Compile PHAR"
              run: php box.phar compile

            - name: "Run phar to see if it works"
              run: php nanbando.phar

            - name: "Checkout gh-pages"
              uses: "actions/checkout@v2"
              with:
                  ref: gh-pages
                  path: gh-pages
                  token: ${{ secrets.PAT }}

            - name: "cp PHAR"
              run: |
                  cp nanbando.phar gh-pages/nanbando.phar

            - name: "Create sha1sum"
              working-directory: gh-pages
              run: |
                  sha1sum nanbando.phar > nanbando.phar.version

            - name: "Configure Git"
              working-directory: gh-pages
              run: |
                  git config user.email "johannes@sulu.io" && \
                  git config user.name "Johannes Wachter"

            - name: "Commit PHAR - master"
              working-directory: gh-pages
              if: "!startsWith(github.ref, 'refs/tags/')"
              run: |
                  git add nanbando.phar nanbando.phar.version && \
                  git commit -m "Updated nanbando to commit ${{ github.event.after }}" && \
                  git push

            - name: "Create Release - tag"
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT }}
              with:
                  files: |
                      nanbando.phar
                      nanbando.phar.pubkey
